# @package hydra.launcher
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.LocalLauncher
timeout_min: 1440  # 1 day
max_num_timeout: 16
# signal_delay_s: 120
cpus_per_task: 4
gpus_per_node: 1
tasks_per_node: 1
mem_gb: 8
nodes: 1
# partition: gpu
submitit_folder: ${hydra.sweep.dir}/.submitit/%j

# additional_parameters:
#   mail-user: "y.hwang@student.tue.nl"
#   mail-type: "FAIL,END"  # Only email if it crashes or finishes